In [1]:
import pandas as pd
from tqdm import tqdm
import numpy as np
import optuna
import warnings
from sklearn.metrics import accuracy_score, balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from catboost import CatBoostClassifier
from catboost.utils import convert_to_onnx_object
from onnxruntime import InferenceSession
from tokenizers import Tokenizer
from onnx.helper import get_attribute_value
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType, Int64TensorType, StringTensorType, guess_tensor_type
from skl2onnx import update_registered_converter
from skl2onnx.common.shape_calculator import calculate_linear_classifier_output_shapes
from skl2onnx._parse import _apply_zipmap, _get_sklearn_operator_name

warnings.filterwarnings('ignore')

In [2]:
DATAPATH = "../../monitorings/meat/predictor/data/meat_dataset_v3.csv"

In [3]:
data_df = pd.read_csv(DATAPATH, index_col=0, sep=';')

data_df['product'] = data_df['product'].str.lower()
data_df['description'] = data_df['description'].str.lower()
data_df

        product                                 description    product_type
0      говядина                                      печень          печень
1      говядина                                       почки           почки
2      говядина                                   почки т/у           почки
3      говядина                              путовый сустав  путовый сустав
4      говядина                                       рубец           рубец
...         ...                                         ...             ...
67709      кура                   тушка 1 сорт,халяль ситно           тушка
67710      кура  фарш механической обвалки,без добавок гост            фарш
67711   индейка                     филе малое тм пава пава     филе грудки
67712      кура                     тушка бк с кожей,мясная           тушка
67713   индейка                             шея микс,халяль             шея

[67714 rows x 3 columns]

In [4]:
model_onnx = InferenceSession("../../monitorings/meat/predictor/data/models/bert/distilbert.onnx", providers=['CPUExecutionProvider'])
tokenizer = Tokenizer.from_file("../../monitorings/meat/predictor/data/models/bert/tokenizer.json")

def onnx_encode(text):
    inputs_tokens = tokenizer.encode(text)
    inputs_onnx = {
        'input_ids': np.expand_dims(np.array(inputs_tokens.ids, dtype=np.int64), axis=0),
        'attention_mask': np.expand_dims(np.array(inputs_tokens.attention_mask, dtype=np.int64), axis=0),
    }
    out_onnx = model_onnx.run(None, inputs_onnx)
    emb_onnx = np.mean(out_onnx[7], axis=1)[0]
    return emb_onnx

embeddings = [onnx_encode(text) for text in tqdm(data_df['description'].values)]
emb_df = pd.DataFrame(embeddings)

100%|██████████| 67714/67714 [10:07<00:00, 111.49it/s]

In [5]:
df_ = pd.concat(
    (data_df.reset_index(), emb_df),
    axis=1
)
df_
df_ = df_.drop(['index', 'description'], axis=1)
df_.columns = df_.columns.astype(str)

In [6]:
df_

,product,product_type,0,1,2,3,4,5,6,7,...,758,759,760,761,762,763,764,765,766,767
0,говядина,печень,-0.084378,-0.097200,0.280494,-0.291216,0.313978,0.231637,0.109654,-0.376657,...,0.014623,-0.474628,-0.205832,0.054644,-0.141018,0.086285,0.263371,0.316369,0.326258,-0.396593
1,говядина,почки,-0.073829,-0.357660,0.276923,-0.324657,0.464376,-0.156408,0.120326,-0.244890,...,-0.005219,-0.305561,-0.410204,0.194652,-0.213833,-0.258648,0.317777,0.014825,0.373704,-0.247354
2,говядина,почки,-0.006886,-0.318581,-0.099874,-0.421789,0.430274,0.175998,0.205775,-0.405187,...,0.042736,-0.646078,0.052179,-0.504751,-0.116105,-0.345333,0.149771,0.197503,0.023801,-0.551336
3,говядина,путовый сустав,-0.214793,-0.100352,0.502717,-0.303248,0.638516,0.041238,0.425129,-0.651608,...,-0.004962,-0.538822,0.166594,-0.272759,0.008362,-0.480042,-0.654679,0.101838,-0.116487,0.418954
4,говядина,рубец,0.166018,-0.125171,0.654533,-0.277937,-0.167207,0.247649,-0.003128,-0.023520,...,-0.244185,-0.576328,0.002645,-0.327170,-0.244775,-0.069312,-0.200902,-0.357261,0.370781,-0.204882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67709,кура,тушка,-0.078524,-0.024507,0.794457,-0.003212,0.348651,-0.099957,0.532231,0.056391,...,-0.055648,-0.553683,-0.154227,0.049127,0.709427,-0.490707,-0.367640,-0.101020,-0.187774,-0.221359
67710,кура,фарш,-0.107442,0.049579,0.247116,-0.056607,0.758417,0.179605,0.517171,0.156283,...,-0.544533,-0.374684,-0.850488,0.034250,-0.557336,-0.393467,-0.096283,0.431568,-0.164349,0.195104
67711,индейка,филе грудки,-0.163904,-0.016655,0.001431,0.009007,0.124267,-0.554389,0.059046,-0.104635,...,-0.216478,-0.199460,-0.402195,0.155833,0.327955,-0.154103,-0.019027,0.029506,0.030942,0.074894
67712,кура,тушка,0.059082,0.424451,0.620753,0.065953,0.152729,0.339374,0.775080,0.355443,...,-0.237648,-0.324552,-0.795738,-0.060622,0.146299,-0.210558,0.230135,0.426331,-0.091269,-0.126149
67713,индейка,шея,-0.221689,-0.084816,0.275613,-0.340094,-0.741893,-0.511102,0.591922,-0.030309,...,0.039496,-0.754440,-0.093666,-0.395091,0.157249,-0.379024,0.004608,0.196247,-0.150191,-0.402491

In [7]:
df_.rename(columns={"product": "category"}, inplace=True)
categories_mapping = {
    'говядина': ['Говядина', 'Телятина', 'Буйволятина', 'Кролик',  'Конина'],
    'свинина': ['Свинина', 'Свиньи'],
    'баранина': ['Баранина', 'Ягнятина'],
    'птица': ['Кура', 'Цыпленок', 'Утка', 'Индейка', 'Цесарка', 'Гусь', 'Перепел', 'Страус', 'Фазан']
}

beef_df = df_[df_['category'].str.capitalize().isin(categories_mapping['говядина'])]
pig_df = df_[df_['category'].str.capitalize().isin(categories_mapping['свинина'])]
mutton_df = df_[df_['category'].str.capitalize().isin(categories_mapping['баранина'])]
bird_df = df_[df_['category'].str.capitalize().isin(categories_mapping['птица'])]

In [8]:
# дублирование категорий с 1 экземпляром
duplicate = mutton_df[mutton_df['product_type'].isin(['бифштекс', 'вымя', 'кость', 'лопаточно-плечевая часть', 'лопаточно-шейная часть', 'лытка', 'набор для гуляша', 'набор для холодца', 'нос', 'пашина', 'пенис', 'шкура'])]
mutton_df = pd.concat((mutton_df, duplicate), axis=0)

duplicate = beef_df[beef_df['product_type'].isin(['каркас', 'крыло', 'спиной отруб', 'шпик хребтовой'])]
beef_df = pd.concat((beef_df, duplicate), axis=0)

duplicate = pig_df[pig_df['product_type'].isin(['губы', 'кожа', 'набор для чахохбили', 'подбедерок', 'спинно-поясничный отруб ', 'четвертины'])]
pig_df = pd.concat((pig_df, duplicate), axis=0)

duplicate = bird_df[bird_df['product_type'].isin(['грудинка', 'гузка', 'мясо механической обвалки', 'седло', 'филе грубки', 'шпик'])]
bird_df = pd.concat((bird_df, duplicate), axis=0)
duplicate = bird_df[bird_df['category'].isin(['фазан'])]
bird_df = pd.concat((bird_df, duplicate), axis=0)

# Тюнинг гиперпараметров

## LogReg

### beef

In [9]:
beef_le = OrdinalEncoder()
beef_df_copy = beef_df.copy()
beef_df_copy['category'] = beef_le.fit_transform(beef_df_copy['category'].values.reshape(-1, 1))
X = beef_df_copy.drop('product_type', axis=1)
y = beef_df_copy['product_type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

def cross_val_train_scores(model, cv):
    splits = cv.split(X_train, y_train)
    cv_scores = []

    for train_i, test_i in splits:
        X_train_fold, X_test_fold = X_train.iloc[train_i], X_train.iloc[test_i]
        y_train_fold, y_test_fold = y_train.iloc[train_i], y_train.iloc[test_i]
        model.fit(X_train_fold, y_train_fold)

        cv_scores.append(balanced_accuracy_score(y_test_fold, model.predict(X_test_fold)))
    return cv_scores

def objective(trial):
    params = {
        'class_weight':'balanced',
    }
    tune_params = {
        'C': trial.suggest_float('C', 0.0001, 2),
    }

    cv = StratifiedKFold(3, shuffle=True, random_state=42)
    scores = cross_val_train_scores(LogisticRegression(**tune_params, **params), cv=cv)

    return np.mean(scores)

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20)

with open('params.txt', 'a', encoding = 'utf-8') as f:
    f.write('beef_logerg' + str(study.best_params) + str(study.best_value) + '\n')

[I 2025-07-01 18:25:51,653] A new study created in memory with name: no-name-b8812498-1e3b-49b0-8b62-fdd5b330ef81
[I 2025-07-01 18:26:14,544] Trial 0 finished with value: 0.8418841061459666 and parameters: {'C': 0.10360687432992541}. Best is trial 0 with value: 0.8418841061459666.
[I 2025-07-01 18:26:47,500] Trial 1 finished with value: 0.8360715196119343 and parameters: {'C': 1.080453163203982}. Best is trial 0 with value: 0.8418841061459666.
[I 2025-07-01 18:27:23,279] Trial 2 finished with value: 0.8365317682608064 and parameters: {'C': 1.0086658227971195}. Best is trial 0 with value: 0.8418841061459666.
[I 2025-07-01 18:27:55,714] Trial 3 finished with value: 0.834513977103057 and parameters: {'C': 1.9173858215887252}. Best is trial 0 with value: 0.8418841061459666.
[I 2025-07-01 18:28:29,377] Trial 4 finished with value: 0.8365709024370641 and parameters: {'C': 1.364821990994408}. Best is trial 0 with value: 0.8418841061459666.
[I 2025-07-01 18:29:04,507] Trial 5 finished with value: 0.8360519054427966 and parameters: {'C': 1.6492811905591236}. Best is trial 0 with value: 0.8418841061459666.
[I 2025-07-01 18:29:33,993] Trial 6 finished with value: 0.8418153430279224 and parameters: {'C': 0.34338743771282154}. Best is trial 0 with value: 0.8418841061459666.
[I 2025-07-01 18:30:08,460] Trial 7 finished with value: 0.8353552055853588 and parameters: {'C': 1.6958957080628565}. Best is trial 0 with value: 0.8418841061459666.
[I 2025-07-01 18:30:41,669] Trial 8 finished with value: 0.8384514563122698 and parameters: {'C': 0.7249971504808872}. Best is trial 0 with value: 0.8418841061459666.
[I 2025-07-01 18:31:14,684] Trial 9 finished with value: 0.8363609850172361 and parameters: {'C': 0.8558668299429935}. Best is trial 0 with value: 0.8418841061459666.
[I 2025-07-01 18:31:45,277] Trial 10 finished with value: 0.840987866621549 and parameters: {'C': 0.02446455480496089}. Best is trial 0 with value: 0.8418841061459666.
[I 2025-07-01 18:32:05,769] Trial 11 finished with value: 0.8448965467724605 and parameters: {'C': 0.059269555634620164}. Best is trial 11 with value: 0.8448965467724605.
[I 2025-07-01 18:32:40,364] Trial 12 finished with value: 0.8447493982095639 and parameters: {'C': 0.03718565014922945}. Best is trial 11 with value: 0.8448965467724605.
[I 2025-07-01 18:33:11,760] Trial 13 finished with value: 0.8407112981314637 and parameters: {'C': 0.4313550764393018}. Best is trial 11 with value: 0.8448965467724605.
[I 2025-07-01 18:33:41,751] Trial 14 finished with value: 0.8390520701266514 and parameters: {'C': 0.5056427281758752}. Best is trial 11 with value: 0.8448965467724605.
[I 2025-07-01 18:34:10,171] Trial 15 finished with value: 0.8421097704630108 and parameters: {'C': 0.27975187615367136}. Best is trial 11 with value: 0.8448965467724605.
[I 2025-07-01 18:34:36,544] Trial 16 finished with value: 0.8435115329172741 and parameters: {'C': 0.04841968022960122}. Best is trial 11 with value: 0.8448965467724605.
[I 2025-07-01 18:35:10,717] Trial 17 finished with value: 0.8411141294750902 and parameters: {'C': 0.5805320911760352}. Best is trial 11 with value: 0.8448965467724605.
[I 2025-07-01 18:35:37,598] Trial 18 finished with value: 0.8402256720284802 and parameters: {'C': 0.2779608415316701}. Best is trial 11 with value: 0.8448965467724605.
[I 2025-07-01 18:36:08,703] Trial 19 finished with value: 0.8377365713734317 and parameters: {'C': 0.698271891880456}. Best is trial 11 with value: 0.8448965467724605.

### pork

In [10]:
# свинина
pig_le = OrdinalEncoder()
pig_df_copy = pig_df.copy()
pig_df_copy['category'] = pig_le.fit_transform(pig_df_copy['category'].values.reshape(-1, 1))
X = pig_df_copy.drop('product_type', axis=1)
y = pig_df_copy['product_type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

def cross_val_train_scores(model, cv):
    splits = cv.split(X_train, y_train)
    cv_scores = []

    for train_i, test_i in splits:
        X_train_fold, X_test_fold = X_train.iloc[train_i], X_train.iloc[test_i]
        y_train_fold, y_test_fold = y_train.iloc[train_i], y_train.iloc[test_i]
        model.fit(X_train_fold, y_train_fold)

        cv_scores.append(balanced_accuracy_score(y_test_fold, model.predict(X_test_fold)))
    return cv_scores

def objective(trial):
    params = {
        'class_weight':'balanced',
    }
    tune_params = {
        'C': trial.suggest_float('C', 0.0001, 2),
    }

    cv = StratifiedKFold(3, shuffle=True, random_state=42)
    scores = cross_val_train_scores(LogisticRegression(**tune_params, **params), cv=cv)

    return np.mean(scores)

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20)

with open('params.txt', 'a', encoding = 'utf-8') as f:
    f.write('pig_logreg' + str(study.best_params) + str(study.best_value) + '\n')

[I 2025-07-01 18:36:08,769] A new study created in memory with name: no-name-3f5003fe-bc31-4f0f-8f6c-1a71af0e9952
[I 2025-07-01 18:36:40,075] Trial 0 finished with value: 0.8449678676719391 and parameters: {'C': 1.7579692455141813}. Best is trial 0 with value: 0.8449678676719391.
[I 2025-07-01 18:37:11,856] Trial 1 finished with value: 0.8443777529504176 and parameters: {'C': 1.3826201118366734}. Best is trial 0 with value: 0.8449678676719391.
[I 2025-07-01 18:37:44,230] Trial 2 finished with value: 0.8410095790879949 and parameters: {'C': 1.87929463360325}. Best is trial 0 with value: 0.8449678676719391.
[I 2025-07-01 18:38:16,558] Trial 3 finished with value: 0.8443180549032693 and parameters: {'C': 1.1684768614853571}. Best is trial 0 with value: 0.8449678676719391.
[I 2025-07-01 18:38:51,191] Trial 4 finished with value: 0.8440898574062564 and parameters: {'C': 1.2732341760480939}. Best is trial 0 with value: 0.8449678676719391.
[I 2025-07-01 18:39:24,926] Trial 5 finished with value: 0.8486906556502344 and parameters: {'C': 1.1910736583488915}. Best is trial 5 with value: 0.8486906556502344.
[I 2025-07-01 18:39:57,383] Trial 6 finished with value: 0.8443633546110592 and parameters: {'C': 1.071601439919022}. Best is trial 5 with value: 0.8486906556502344.
[I 2025-07-01 18:40:32,106] Trial 7 finished with value: 0.8421647474269415 and parameters: {'C': 1.7551998029609674}. Best is trial 5 with value: 0.8486906556502344.
[I 2025-07-01 18:41:00,582] Trial 8 finished with value: 0.8523998221916834 and parameters: {'C': 0.34235857212705934}. Best is trial 8 with value: 0.8523998221916834.
[I 2025-07-01 18:41:27,552] Trial 9 finished with value: 0.8550069529508896 and parameters: {'C': 0.25481644439042445}. Best is trial 9 with value: 0.8550069529508896.
[I 2025-07-01 18:42:01,507] Trial 10 finished with value: 0.8484658566662612 and parameters: {'C': 0.024564432170036565}. Best is trial 9 with value: 0.8550069529508896.
[I 2025-07-01 18:42:29,206] Trial 11 finished with value: 0.8537739664622436 and parameters: {'C': 0.2975828609806476}. Best is trial 9 with value: 0.8550069529508896.
[I 2025-07-01 18:42:59,678] Trial 12 finished with value: 0.8535265213905486 and parameters: {'C': 0.5897614771323257}. Best is trial 9 with value: 0.8550069529508896.
[I 2025-07-01 18:43:29,805] Trial 13 finished with value: 0.8452526673025877 and parameters: {'C': 0.6942722053873278}. Best is trial 9 with value: 0.8550069529508896.
[I 2025-07-01 18:44:06,378] Trial 14 finished with value: 0.8535315076043924 and parameters: {'C': 0.0431924785712306}. Best is trial 9 with value: 0.8550069529508896.
[I 2025-07-01 18:44:35,851] Trial 15 finished with value: 0.8516396131566205 and parameters: {'C': 0.3241970909232571}. Best is trial 9 with value: 0.8550069529508896.
[I 2025-07-01 18:45:18,883] Trial 16 finished with value: 0.8489893501340706 and parameters: {'C': 0.7791358639653843}. Best is trial 9 with value: 0.8550069529508896.
[I 2025-07-01 18:45:57,157] Trial 17 finished with value: 0.8518434455214035 and parameters: {'C': 0.3412272041491472}. Best is trial 9 with value: 0.8550069529508896.
[I 2025-07-01 18:46:42,352] Trial 18 finished with value: 0.8489490941244089 and parameters: {'C': 0.5169428344370266}. Best is trial 9 with value: 0.8550069529508896.
[I 2025-07-01 18:47:19,564] Trial 19 finished with value: 0.8490136841094 and parameters: {'C': 0.8240270962106462}. Best is trial 9 with value: 0.8550069529508896.

### mutton

In [11]:
print("Анализ классов product_type для баранины:")
class_counts = mutton_df['product_type'].value_counts()
print(f"Всего классов: {len(class_counts)}")
print(f"\nКлассы с менее чем 5 образцами:")
print(class_counts[class_counts < 5].sort_values())
print(f"\nКлассы с 1 образцом:")
print(class_counts[class_counts == 1])

Анализ классов product_type для баранины:
Всего классов: 69

Классы с менее чем 5 образцами:
product_type
грудной отруб             1
селезенка                 1
легкое                    1
жилка                     1
мякоть                    1
уши                       1
тонкий край               1
шейно-лопаточный отруб    1
поджарка                  1
набор для студня          1
кострец                   2
толстый край              2
хвосты                    2
рагу                      2
набор для гуляша          2
бифштекс                  2
диафрагма                 2
рулька                    2
кости                     2
рубец                     2
губы                      2
набор для бульона         2
трахея                    2
медальон                  3
печень                    3
сердце                    3
спинной отруб             3
шейный отруб              3
почки                     3
калтык                    4
обрезь                    4
субпродукты               4
набор для плова           4
Name: count, dtype: int64

Классы с 1 образцом:
product_type
поджарка                  1
грудной отруб             1
селезенка                 1
легкое                    1
жилка                     1
мякоть                    1
уши                       1
тонкий край               1
шейно-лопаточный отруб    1
набор для студня          1
Name: count, dtype: int64

In [12]:
# баранина
min_samples = 5
class_counts = mutton_df['product_type'].value_counts()
classes_to_duplicate = class_counts[class_counts < min_samples].index
valid_classes = class_counts[class_counts >= min_samples].index

# Подсчёт статистики
total_classes_before = len(class_counts)
classes_duplicated = len(classes_to_duplicate)
unique_classes_duplicated = len(set(classes_to_duplicate))

print(f"Всего классов до обработки: {total_classes_before}")
print(f"Классов с менее чем {min_samples} образцами: {classes_duplicated}")
print(f"Уникальных классов для дублирования: {unique_classes_duplicated}")

# Дублирование образцов для классов с недостаточным количеством
mutton_df_duplicated = mutton_df.copy()
for class_name in classes_to_duplicate:
    class_samples = mutton_df[mutton_df['product_type'] == class_name]
    needed_copies = min_samples - len(class_samples)
    
    # Дублируем образцы до достижения min_samples
    for _ in range(needed_copies):
        mutton_df_duplicated = pd.concat([mutton_df_duplicated, class_samples], ignore_index=True)

print(f"Всего образцов после дублирования: {len(mutton_df_duplicated)}")

mutton_le = OrdinalEncoder()
mutton_df_copy = mutton_df_duplicated.copy()
mutton_df_copy['category'] = mutton_le.fit_transform(mutton_df_copy['category'].values.reshape(-1, 1))
X = mutton_df_copy.drop('product_type', axis=1)
y = mutton_df_copy['product_type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

def cross_val_train_scores(model, cv):
    splits = cv.split(X_train, y_train)
    cv_scores = []

    for train_i, test_i in splits:
        X_train_fold, X_test_fold = X_train.iloc[train_i], X_train.iloc[test_i]
        y_train_fold, y_test_fold = y_train.iloc[train_i], y_train.iloc[test_i]
        model.fit(X_train_fold, y_train_fold)

        cv_scores.append(balanced_accuracy_score(y_test_fold, model.predict(X_test_fold)))
    return cv_scores

def objective(trial):
    params = {
        'class_weight':'balanced',
    }
    tune_params = {
        'C': trial.suggest_float('C', 0.0001, 2),
    }
    cv = StratifiedKFold(5, shuffle=True, random_state=42)
    scores = cross_val_train_scores(LogisticRegression(**tune_params, **params), cv=cv)
    return np.mean(scores)

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20)

with open('params.txt', 'a', encoding = 'utf-8') as f:
    f.write('mutton_logreg' + str(study.best_params) + str(study.best_value) + '\n')

[I 2025-07-01 18:47:19,677] A new study created in memory with name: no-name-f0a651f1-a982-49e3-91d2-c65a8389426e

Всего классов до обработки: 69
Классов с менее чем 5 образцами: 33
Уникальных классов для дублирования: 33
Всего образцов после дублирования: 1005

[I 2025-07-01 18:48:12,973] Trial 0 finished with value: 0.8710045324801691 and parameters: {'C': 0.3613217052503698}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:49:03,382] Trial 1 finished with value: 0.8675157671564607 and parameters: {'C': 0.6634411814097911}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:50:05,140] Trial 2 finished with value: 0.8668139308663892 and parameters: {'C': 0.5627839884303237}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:50:55,946] Trial 3 finished with value: 0.8680814555570923 and parameters: {'C': 0.2334450365641685}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:51:29,856] Trial 4 finished with value: 0.8676879830003184 and parameters: {'C': 1.950732086337983}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:52:20,674] Trial 5 finished with value: 0.8710045324801691 and parameters: {'C': 0.3664353041091828}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:52:51,581] Trial 6 finished with value: 0.8684232771179653 and parameters: {'C': 1.0163319347331867}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:53:25,796] Trial 7 finished with value: 0.8676879830003184 and parameters: {'C': 1.395281530407243}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:54:01,785] Trial 8 finished with value: 0.8676879830003184 and parameters: {'C': 1.4936135258786525}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:54:48,654] Trial 9 finished with value: 0.8663074126065785 and parameters: {'C': 0.18540750454361524}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:55:04,008] Trial 10 finished with value: 0.7990887026388562 and parameters: {'C': 0.009108160720825764}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:56:02,938] Trial 11 finished with value: 0.8673041269448205 and parameters: {'C': 0.5915615620783758}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:56:35,181] Trial 12 finished with value: 0.8673380635964042 and parameters: {'C': 0.8087002289859602}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:57:28,718] Trial 13 finished with value: 0.8680633560095808 and parameters: {'C': 0.367072441323159}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:58:01,014] Trial 14 finished with value: 0.8684232771179653 and parameters: {'C': 0.9478034334696694}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:58:09,694] Trial 15 finished with value: 0.7401041472591078 and parameters: {'C': 0.0014276661461832818}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:59:04,861] Trial 16 finished with value: 0.8680633560095808 and parameters: {'C': 0.40874516269174}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 18:59:36,470] Trial 17 finished with value: 0.8676879830003184 and parameters: {'C': 1.0933357689304142}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 19:00:08,533] Trial 18 finished with value: 0.8676879830003184 and parameters: {'C': 1.3185092451028757}. Best is trial 0 with value: 0.8710045324801691.
[I 2025-07-01 19:01:01,965] Trial 19 finished with value: 0.8672941252403501 and parameters: {'C': 0.415142988313354}. Best is trial 0 with value: 0.8710045324801691.

### bird

In [13]:
# птица
bird_le = OrdinalEncoder()
bird_df_copy = bird_df.copy()
bird_df_copy['category'] = bird_le.fit_transform(bird_df_copy['category'].values.reshape(-1, 1))
X = bird_df_copy.drop('product_type', axis=1)
y = bird_df_copy['product_type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

def cross_val_train_scores(model, cv):
    splits = cv.split(X_train, y_train)
    cv_scores = []

    for train_i, test_i in splits:
        X_train_fold, X_test_fold = X_train.iloc[train_i], X_train.iloc[test_i]
        y_train_fold, y_test_fold = y_train.iloc[train_i], y_train.iloc[test_i]
        model.fit(X_train_fold, y_train_fold)

        cv_scores.append(balanced_accuracy_score(y_test_fold, model.predict(X_test_fold)))
    return cv_scores

def objective(trial):
    params = {
        'class_weight':'balanced',
    }
    tune_params = {
        'C': trial.suggest_float('C', 0.0001, 2),
    }

    cv = StratifiedKFold(3, shuffle=True, random_state=42)
    scores = cross_val_train_scores(LogisticRegression(**tune_params, **params), cv=cv)
    return np.mean(scores)

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20)

with open('params.txt', 'a', encoding = 'utf-8') as f:
    f.write('bird_logreg' + str(study.best_params) + str(study.best_value) + '\n')

[I 2025-07-01 19:01:02,136] A new study created in memory with name: no-name-942f6352-8ced-44da-bf92-84266809cbc5
[I 2025-07-01 19:02:04,147] Trial 0 finished with value: 0.8422424032700765 and parameters: {'C': 0.3954660267636226}. Best is trial 0 with value: 0.8422424032700765.
[I 2025-07-01 19:03:07,737] Trial 1 finished with value: 0.8321724002351815 and parameters: {'C': 1.466429165471729}. Best is trial 0 with value: 0.8422424032700765.
[I 2025-07-01 19:04:11,600] Trial 2 finished with value: 0.8330660756250268 and parameters: {'C': 1.0284422481989453}. Best is trial 0 with value: 0.8422424032700765.
[I 2025-07-01 19:05:16,566] Trial 3 finished with value: 0.8332830834437286 and parameters: {'C': 0.9979627248415986}. Best is trial 0 with value: 0.8422424032700765.
[I 2025-07-01 19:06:15,013] Trial 4 finished with value: 0.8406842934237776 and parameters: {'C': 0.151936584464412}. Best is trial 0 with value: 0.8422424032700765.
[I 2025-07-01 19:07:19,249] Trial 5 finished with value: 0.8332836432683505 and parameters: {'C': 1.5295954712239979}. Best is trial 0 with value: 0.8422424032700765.
[I 2025-07-01 19:08:22,553] Trial 6 finished with value: 0.8404708520801091 and parameters: {'C': 0.42106692826027464}. Best is trial 0 with value: 0.8422424032700765.
[I 2025-07-01 19:09:27,207] Trial 7 finished with value: 0.832308492884179 and parameters: {'C': 1.1842055403555565}. Best is trial 0 with value: 0.8422424032700765.
[I 2025-07-01 19:10:29,323] Trial 8 finished with value: 0.8302896224418962 and parameters: {'C': 1.6185819674320112}. Best is trial 0 with value: 0.8422424032700765.
[I 2025-07-01 19:11:33,258] Trial 9 finished with value: 0.841897890038234 and parameters: {'C': 0.48238113316395437}. Best is trial 0 with value: 0.8422424032700765.
[I 2025-07-01 19:12:27,292] Trial 10 finished with value: 0.8434490449672403 and parameters: {'C': 0.019633761506220926}. Best is trial 10 with value: 0.8434490449672403.
[I 2025-07-01 19:13:13,457] Trial 11 finished with value: 0.842247615524438 and parameters: {'C': 0.06391825916782123}. Best is trial 10 with value: 0.8434490449672403.
[I 2025-07-01 19:13:59,442] Trial 12 finished with value: 0.842167342169391 and parameters: {'C': 0.0791811101975251}. Best is trial 10 with value: 0.8434490449672403.
[I 2025-07-01 19:14:56,684] Trial 13 finished with value: 0.8340436067516764 and parameters: {'C': 0.7128577047858166}. Best is trial 10 with value: 0.8434490449672403.
[I 2025-07-01 19:15:54,114] Trial 14 finished with value: 0.8229679875549176 and parameters: {'C': 1.9990420931742716}. Best is trial 10 with value: 0.8434490449672403.
[I 2025-07-01 19:16:50,137] Trial 15 finished with value: 0.8430217740846068 and parameters: {'C': 0.013990417022637683}. Best is trial 10 with value: 0.8434490449672403.
[I 2025-07-01 19:17:47,679] Trial 16 finished with value: 0.8342161117589476 and parameters: {'C': 0.674097529078397}. Best is trial 10 with value: 0.8434490449672403.
[I 2025-07-01 19:18:43,391] Trial 17 finished with value: 0.8403485088077257 and parameters: {'C': 0.2675927807864701}. Best is trial 10 with value: 0.8434490449672403.
[I 2025-07-01 19:19:41,662] Trial 18 finished with value: 0.8349242215697795 and parameters: {'C': 0.6882045911773551}. Best is trial 10 with value: 0.8434490449672403.
[I 2025-07-01 19:20:21,873] Trial 19 finished with value: 0.8435994511570725 and parameters: {'C': 0.03602531078286672}. Best is trial 19 with value: 0.8435994511570725.

## CatBoost

### beef

In [14]:
beef_le = OrdinalEncoder()
beef_df_copy = beef_df.copy()
beef_df_copy['category'] = beef_le.fit_transform(beef_df_copy['category'].values.reshape(-1, 1))
X = beef_df_copy.drop('product_type', axis=1)
y = beef_df_copy['product_type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

def objective(trial):
    params = {
        'verbose': False,
        'loss_function': 'MultiClassOneVsAll',
        'eval_metric': 'Accuracy',
        'task_type': 'GPU',
        'random_seed': 42,
        'border_count': 254
    }
    tune_params = {
        'depth': trial.suggest_int('depth', 3, 5),
        'iterations': trial.suggest_int('iterations', 1000, 2000),
        'learning_rate': trial.suggest_float("learning_rate", 0.03, 0.3),
        'l2_leaf_reg': trial.suggest_float("l2_leaf_reg", 1.0, 50.0),
        'random_strength': trial.suggest_float("random_strength", 1.0, 10.0),
        'fold_permutation_block': trial.suggest_int('fold_permutation_block', 2, 10),
        'auto_class_weights': trial.suggest_categorical("auto_class_weights", ["SqrtBalanced", "Balanced"]),
        # 'colsample_bylevel': trial.suggest_float('colsample_bylevel', 0.5, 1.0),
    }
    catbos_model = CatBoostClassifier(**tune_params, **params)
    catbos_model.fit(
        X=X_train,
        y=y_train,
        use_best_model=True,
        eval_set=(X_test, y_test),
        early_stopping_rounds=100
    )
    test_preds = catbos_model.predict(X_test)
    return accuracy_score(y_test, test_preds)

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20)

with open('params.txt', 'a', encoding = 'utf-8') as f:
    f.write('beef_catboost' + str(study.best_params) + 'weighted accuracy' + str(study.best_value) + '\n')

[I 2025-07-01 19:20:21,938] A new study created in memory with name: no-name-480e3ada-4ac2-4e1a-b362-0ea23bde7519
[I 2025-07-01 19:23:01,081] Trial 0 finished with value: 0.9274193548387096 and parameters: {'depth': 3, 'iterations': 1386, 'learning_rate': 0.209220532717232, 'l2_leaf_reg': 29.537172564242073, 'random_strength': 9.41183317971555, 'fold_permutation_block': 8, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 0 with value: 0.9274193548387096.
[I 2025-07-01 19:25:53,374] Trial 1 finished with value: 0.9144265232974911 and parameters: {'depth': 4, 'iterations': 1030, 'learning_rate': 0.2676362130375013, 'l2_leaf_reg': 49.73538578071331, 'random_strength': 7.393408608899964, 'fold_permutation_block': 8, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 0 with value: 0.9274193548387096.
[I 2025-07-01 19:27:36,372] Trial 2 finished with value: 0.9094982078853047 and parameters: {'depth': 3, 'iterations': 1949, 'learning_rate': 0.11517061835321336, 'l2_leaf_reg': 24.571764948107777, 'random_strength': 6.914323664893966, 'fold_permutation_block': 3, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 0 with value: 0.9274193548387096.
[I 2025-07-01 19:29:12,232] Trial 3 finished with value: 0.900089605734767 and parameters: {'depth': 3, 'iterations': 1681, 'learning_rate': 0.24947997064830074, 'l2_leaf_reg': 46.9375628975175, 'random_strength': 5.789154161643614, 'fold_permutation_block': 2, 'auto_class_weights': 'Balanced'}. Best is trial 0 with value: 0.9274193548387096.
[I 2025-07-01 19:31:03,644] Trial 4 finished with value: 0.9278673835125448 and parameters: {'depth': 3, 'iterations': 1961, 'learning_rate': 0.24211334049159006, 'l2_leaf_reg': 7.0422324402524605, 'random_strength': 9.325586023176506, 'fold_permutation_block': 4, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 4 with value: 0.9278673835125448.
[I 2025-07-01 19:33:32,028] Trial 5 finished with value: 0.9269713261648745 and parameters: {'depth': 4, 'iterations': 1567, 'learning_rate': 0.26601702125640825, 'l2_leaf_reg': 11.688319429350061, 'random_strength': 9.519992309699498, 'fold_permutation_block': 10, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 4 with value: 0.9278673835125448.
[I 2025-07-01 19:35:02,203] Trial 6 finished with value: 0.8969534050179212 and parameters: {'depth': 3, 'iterations': 1600, 'learning_rate': 0.24813922941968905, 'l2_leaf_reg': 27.5582075798757, 'random_strength': 5.997314667229205, 'fold_permutation_block': 2, 'auto_class_weights': 'Balanced'}. Best is trial 4 with value: 0.9278673835125448.
[I 2025-07-01 19:39:51,272] Trial 7 finished with value: 0.9265232974910395 and parameters: {'depth': 5, 'iterations': 1275, 'learning_rate': 0.2808519591151992, 'l2_leaf_reg': 7.112431015796863, 'random_strength': 7.416007454920434, 'fold_permutation_block': 6, 'auto_class_weights': 'Balanced'}. Best is trial 4 with value: 0.9278673835125448.
[I 2025-07-01 19:42:20,048] Trial 8 finished with value: 0.8956093189964157 and parameters: {'depth': 5, 'iterations': 1610, 'learning_rate': 0.09840255357307139, 'l2_leaf_reg': 15.814675531447591, 'random_strength': 7.129188518350046, 'fold_permutation_block': 2, 'auto_class_weights': 'Balanced'}. Best is trial 4 with value: 0.9278673835125448.
[I 2025-07-01 19:47:41,631] Trial 9 finished with value: 0.9260752688172043 and parameters: {'depth': 5, 'iterations': 1736, 'learning_rate': 0.08102479381977976, 'l2_leaf_reg': 8.493867971981524, 'random_strength': 6.236785568273493, 'fold_permutation_block': 10, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 4 with value: 0.9278673835125448.
[I 2025-07-01 19:52:06,079] Trial 10 finished with value: 0.9202508960573477 and parameters: {'depth': 4, 'iterations': 1971, 'learning_rate': 0.03001873724263951, 'l2_leaf_reg': 2.104950503844483, 'random_strength': 2.515357612610308, 'fold_permutation_block': 5, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 4 with value: 0.9278673835125448.
[I 2025-07-01 19:54:14,392] Trial 11 finished with value: 0.9198028673835126 and parameters: {'depth': 3, 'iterations': 1362, 'learning_rate': 0.19549667921639682, 'l2_leaf_reg': 33.684187666942705, 'random_strength': 9.932895378254317, 'fold_permutation_block': 8, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 4 with value: 0.9278673835125448.
[I 2025-07-01 19:56:37,390] Trial 12 finished with value: 0.9157706093189965 and parameters: {'depth': 3, 'iterations': 1342, 'learning_rate': 0.1861209169323457, 'l2_leaf_reg': 37.232817058186654, 'random_strength': 8.693098206890914, 'fold_permutation_block': 4, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 4 with value: 0.9278673835125448.
[I 2025-07-01 19:57:58,036] Trial 13 finished with value: 0.910394265232975 and parameters: {'depth': 3, 'iterations': 1147, 'learning_rate': 0.20718111541666565, 'l2_leaf_reg': 19.075792092615565, 'random_strength': 2.72799663510492, 'fold_permutation_block': 8, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 4 with value: 0.9278673835125448.
[I 2025-07-01 20:01:54,236] Trial 14 finished with value: 0.9220430107526881 and parameters: {'depth': 4, 'iterations': 1810, 'learning_rate': 0.1544041302260773, 'l2_leaf_reg': 37.20939112288007, 'random_strength': 4.59168720086338, 'fold_permutation_block': 6, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 4 with value: 0.9278673835125448.
[I 2025-07-01 20:03:54,402] Trial 15 finished with value: 0.9166666666666666 and parameters: {'depth': 4, 'iterations': 1438, 'learning_rate': 0.22329852576238785, 'l2_leaf_reg': 25.250200254768444, 'random_strength': 8.659861212072695, 'fold_permutation_block': 7, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 4 with value: 0.9278673835125448.
[I 2025-07-01 20:05:36,974] Trial 16 finished with value: 0.9220430107526881 and parameters: {'depth': 3, 'iterations': 1838, 'learning_rate': 0.16045162831522733, 'l2_leaf_reg': 19.109456115471552, 'random_strength': 4.363265978663122, 'fold_permutation_block': 4, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 4 with value: 0.9278673835125448.
[I 2025-07-01 20:07:36,479] Trial 17 finished with value: 0.918010752688172 and parameters: {'depth': 3, 'iterations': 1172, 'learning_rate': 0.29598822889766685, 'l2_leaf_reg': 30.48710591435612, 'random_strength': 1.1977044088072164, 'fold_permutation_block': 9, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 4 with value: 0.9278673835125448.
[I 2025-07-01 20:08:18,527] Trial 18 finished with value: 0.8579749103942652 and parameters: {'depth': 3, 'iterations': 1470, 'learning_rate': 0.2298500992207521, 'l2_leaf_reg': 42.93168322567001, 'random_strength': 8.543333116643144, 'fold_permutation_block': 5, 'auto_class_weights': 'Balanced'}. Best is trial 4 with value: 0.9278673835125448.
[I 2025-07-01 20:10:40,864] Trial 19 finished with value: 0.9242831541218638 and parameters: {'depth': 4, 'iterations': 1860, 'learning_rate': 0.1417407123742501, 'l2_leaf_reg': 2.4867316142007763, 'random_strength': 9.126570004584748, 'fold_permutation_block': 5, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 4 with value: 0.9278673835125448.

### pork

In [15]:
pig_le = OrdinalEncoder()
pig_df_copy = pig_df.copy()
pig_df_copy['category'] = pig_le.fit_transform(pig_df_copy['category'].values.reshape(-1, 1))
X = pig_df_copy.drop('product_type', axis=1)
y = pig_df_copy['product_type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

def objective(trial):
    params = {
        'verbose': False,
        'loss_function': 'MultiClassOneVsAll',
        'eval_metric': 'Accuracy',
        'task_type': 'GPU',
        'random_seed': 42,
        'border_count': 254
    }
    tune_params = {
        'depth': trial.suggest_int('depth', 3, 5),
        'iterations': trial.suggest_int('iterations', 1000, 2000),
        'learning_rate': trial.suggest_float("learning_rate", 0.03, 0.3),
        'l2_leaf_reg': trial.suggest_float("l2_leaf_reg", 10.0, 100.0),
        'random_strength': trial.suggest_float("random_strength", 3.0, 20.0),
        'fold_permutation_block': trial.suggest_int('fold_permutation_block', 2, 10),
        'auto_class_weights': trial.suggest_categorical("auto_class_weights", ["SqrtBalanced", "Balanced"]),
        # 'colsample_bylevel': trial.suggest_float('colsample_bylevel', 0.5, 1.0),
    }
    catbos_model = CatBoostClassifier(**tune_params, **params)
    catbos_model.fit(
        X=X_train,
        y=y_train,
        use_best_model=True,
        eval_set=(X_test, y_test),
        early_stopping_rounds=100
    )
    test_preds = catbos_model.predict(X_test)
    return accuracy_score(y_test, test_preds)

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20)

with open('params.txt', 'a', encoding = 'utf-8') as f:
    f.write('pig_catboost' + str(study.best_params) + 'weighted accuracy' + str(study.best_value) + '\n')

[I 2025-07-01 20:10:40,915] A new study created in memory with name: no-name-cd41e016-82d7-4a68-bc55-5df4e2c30c36
[I 2025-07-01 20:15:37,599] Trial 0 finished with value: 0.9336714787358564 and parameters: {'depth': 5, 'iterations': 1579, 'learning_rate': 0.27351452141187227, 'l2_leaf_reg': 92.39695681777434, 'random_strength': 11.897974903583934, 'fold_permutation_block': 7, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 0 with value: 0.9336714787358564.
[I 2025-07-01 20:17:12,186] Trial 1 finished with value: 0.9289894654701522 and parameters: {'depth': 3, 'iterations': 1124, 'learning_rate': 0.23511642282660375, 'l2_leaf_reg': 53.45224820735204, 'random_strength': 11.587600586458151, 'fold_permutation_block': 2, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 0 with value: 0.9336714787358564.
[I 2025-07-01 20:18:27,805] Trial 2 finished with value: 0.887241513850956 and parameters: {'depth': 3, 'iterations': 1763, 'learning_rate': 0.049521929917296766, 'l2_leaf_reg': 68.5745693519092, 'random_strength': 3.245425660405668, 'fold_permutation_block': 4, 'auto_class_weights': 'Balanced'}. Best is trial 0 with value: 0.9336714787358564.
[I 2025-07-01 20:20:33,405] Trial 3 finished with value: 0.9352321498244245 and parameters: {'depth': 4, 'iterations': 1506, 'learning_rate': 0.20507151526765005, 'l2_leaf_reg': 43.97163747493944, 'random_strength': 17.526600809157102, 'fold_permutation_block': 2, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 3 with value: 0.9352321498244245.
[I 2025-07-01 20:21:39,894] Trial 4 finished with value: 0.9087007413187671 and parameters: {'depth': 3, 'iterations': 1176, 'learning_rate': 0.2175735077712678, 'l2_leaf_reg': 97.81946579165273, 'random_strength': 7.693647223696796, 'fold_permutation_block': 5, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 3 with value: 0.9352321498244245.
[I 2025-07-01 20:22:48,901] Trial 5 finished with value: 0.9243074522044479 and parameters: {'depth': 3, 'iterations': 1929, 'learning_rate': 0.17806493373711924, 'l2_leaf_reg': 55.02157162330543, 'random_strength': 5.684205004940711, 'fold_permutation_block': 4, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 3 with value: 0.9352321498244245.
[I 2025-07-01 20:24:29,451] Trial 6 finished with value: 0.9047990635973469 and parameters: {'depth': 5, 'iterations': 1297, 'learning_rate': 0.15209391238582087, 'l2_leaf_reg': 65.71749215140167, 'random_strength': 15.80560156990738, 'fold_permutation_block': 3, 'auto_class_weights': 'Balanced'}. Best is trial 3 with value: 0.9352321498244245.
[I 2025-07-01 20:27:15,444] Trial 7 finished with value: 0.9360124853687085 and parameters: {'depth': 5, 'iterations': 1779, 'learning_rate': 0.10445006120225968, 'l2_leaf_reg': 15.967075134581009, 'random_strength': 18.529679814116236, 'fold_permutation_block': 4, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 7 with value: 0.9360124853687085.
[I 2025-07-01 20:30:07,430] Trial 8 finished with value: 0.9321108076472884 and parameters: {'depth': 4, 'iterations': 1985, 'learning_rate': 0.16257255090109726, 'l2_leaf_reg': 53.96456209305417, 'random_strength': 5.1071555098573675, 'fold_permutation_block': 7, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 7 with value: 0.9360124853687085.
[I 2025-07-01 20:31:01,989] Trial 9 finished with value: 0.9317206398751463 and parameters: {'depth': 3, 'iterations': 1845, 'learning_rate': 0.16122457595143772, 'l2_leaf_reg': 12.327862815854779, 'random_strength': 18.984422018040608, 'fold_permutation_block': 3, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 7 with value: 0.9360124853687085.
[I 2025-07-01 20:32:59,881] Trial 10 finished with value: 0.9133827545844713 and parameters: {'depth': 5, 'iterations': 1674, 'learning_rate': 0.0666907899878797, 'l2_leaf_reg': 12.286731990710841, 'random_strength': 14.757706662073314, 'fold_permutation_block': 10, 'auto_class_weights': 'Balanced'}. Best is trial 7 with value: 0.9360124853687085.
[I 2025-07-01 20:34:56,806] Trial 11 finished with value: 0.9285992976980102 and parameters: {'depth': 4, 'iterations': 1419, 'learning_rate': 0.10065195772857037, 'l2_leaf_reg': 31.242179429488818, 'random_strength': 19.918839326072202, 'fold_permutation_block': 2, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 7 with value: 0.9360124853687085.
[I 2025-07-01 20:36:54,599] Trial 12 finished with value: 0.9301599687865783 and parameters: {'depth': 4, 'iterations': 1491, 'learning_rate': 0.1146664873123885, 'l2_leaf_reg': 30.754908147851083, 'random_strength': 16.693642437361486, 'fold_permutation_block': 6, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 7 with value: 0.9360124853687085.
[I 2025-07-01 20:39:54,640] Trial 13 finished with value: 0.9371829886851346 and parameters: {'depth': 5, 'iterations': 1664, 'learning_rate': 0.21384214801999102, 'l2_leaf_reg': 31.460470832453527, 'random_strength': 17.770338490574982, 'fold_permutation_block': 4, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 13 with value: 0.9371829886851346.
[I 2025-07-01 20:41:11,993] Trial 14 finished with value: 0.9110417479516192 and parameters: {'depth': 5, 'iterations': 1663, 'learning_rate': 0.2981547514402494, 'l2_leaf_reg': 31.764772386327532, 'random_strength': 13.819448999150671, 'fold_permutation_block': 5, 'auto_class_weights': 'Balanced'}. Best is trial 13 with value: 0.9371829886851346.
[I 2025-07-01 20:43:54,984] Trial 15 finished with value: 0.9309403043308623 and parameters: {'depth': 5, 'iterations': 1781, 'learning_rate': 0.09422960368548919, 'l2_leaf_reg': 21.282845100548244, 'random_strength': 9.574623228368637, 'fold_permutation_block': 8, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 13 with value: 0.9371829886851346.
[I 2025-07-01 20:47:26,371] Trial 16 finished with value: 0.9364026531408506 and parameters: {'depth': 5, 'iterations': 1668, 'learning_rate': 0.12707854933642215, 'l2_leaf_reg': 23.429021323015096, 'random_strength': 18.544418920088972, 'fold_permutation_block': 4, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 13 with value: 0.9371829886851346.
[I 2025-07-01 20:49:18,009] Trial 17 finished with value: 0.9364026531408506 and parameters: {'depth': 4, 'iterations': 1344, 'learning_rate': 0.24846637908771885, 'l2_leaf_reg': 39.90807596310934, 'random_strength': 13.307648129062503, 'fold_permutation_block': 5, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 13 with value: 0.9371829886851346.
[I 2025-07-01 20:50:54,082] Trial 18 finished with value: 0.9153335934451814 and parameters: {'depth': 5, 'iterations': 1623, 'learning_rate': 0.13769598788418133, 'l2_leaf_reg': 21.968329996245018, 'random_strength': 16.183957547071437, 'fold_permutation_block': 6, 'auto_class_weights': 'Balanced'}. Best is trial 13 with value: 0.9371829886851346.
[I 2025-07-01 20:53:52,699] Trial 19 finished with value: 0.9356223175965666 and parameters: {'depth': 5, 'iterations': 1036, 'learning_rate': 0.2047799740664829, 'l2_leaf_reg': 42.3762444457486, 'random_strength': 9.552101185332067, 'fold_permutation_block': 10, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 13 with value: 0.9371829886851346.

### mutton

In [16]:
mutton_le = OrdinalEncoder()
mutton_df_copy = mutton_df_duplicated.copy()
mutton_df_copy['category'] = mutton_le.fit_transform(mutton_df_copy['category'].values.reshape(-1, 1))
X = mutton_df_copy.drop('product_type', axis=1)
y = mutton_df_copy['product_type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

def objective(trial):
    params = {
        'verbose': False,
        'loss_function': 'MultiClassOneVsAll',
        'eval_metric': 'Accuracy',
        'task_type': 'GPU',
        'random_seed': 42,
        'border_count': 254
    }
    tune_params = {
        'depth': trial.suggest_int('depth', 3, 5),
        'iterations': trial.suggest_int('iterations', 100, 2000),
        'learning_rate': trial.suggest_float("learning_rate", 0.03, 0.3),
        'l2_leaf_reg': trial.suggest_float("l2_leaf_reg", 10.0, 100.0),
        'random_strength': trial.suggest_float("random_strength", 5.0, 30.0),
        'fold_permutation_block': trial.suggest_int('fold_permutation_block', 2, 10),
        'auto_class_weights': trial.suggest_categorical("auto_class_weights", ["SqrtBalanced", "Balanced"]),
        # 'colsample_bylevel': trial.suggest_float('colsample_bylevel', 0.5, 1.0),
    }
    catbos_model = CatBoostClassifier(**tune_params, **params)
    catbos_model.fit(
        X=X_train,
        y=y_train,
        use_best_model=True,
        eval_set=(X_test, y_test),
        early_stopping_rounds=100
    )
    test_preds = catbos_model.predict(X_test)
    return accuracy_score(y_test, test_preds)

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=40)

with open('params.txt', 'a', encoding = 'utf-8') as f:
    f.write('mutton_catboost' + str(study.best_params) + 'weighted accuracy' + str(study.best_value) + '\n')

[I 2025-07-01 20:53:52,716] A new study created in memory with name: no-name-ba90a7a2-4767-459e-87c7-c7dc6de29528
[I 2025-07-01 20:54:33,503] Trial 0 finished with value: 0.8507462686567164 and parameters: {'depth': 4, 'iterations': 1346, 'learning_rate': 0.2711634802643364, 'l2_leaf_reg': 21.81611212904169, 'random_strength': 25.751880641395275, 'fold_permutation_block': 8, 'auto_class_weights': 'Balanced'}. Best is trial 0 with value: 0.8507462686567164.
[I 2025-07-01 20:55:23,706] Trial 1 finished with value: 0.8805970149253731 and parameters: {'depth': 5, 'iterations': 1773, 'learning_rate': 0.21331734803807034, 'l2_leaf_reg': 10.163533732195859, 'random_strength': 7.893342654392297, 'fold_permutation_block': 5, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 20:56:14,471] Trial 2 finished with value: 0.835820895522388 and parameters: {'depth': 5, 'iterations': 846, 'learning_rate': 0.22925181399524358, 'l2_leaf_reg': 78.45986551444008, 'random_strength': 19.517044998512137, 'fold_permutation_block': 7, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 20:56:59,024] Trial 3 finished with value: 0.8606965174129353 and parameters: {'depth': 4, 'iterations': 737, 'learning_rate': 0.22545662295269425, 'l2_leaf_reg': 54.22365314568209, 'random_strength': 8.868142906179456, 'fold_permutation_block': 7, 'auto_class_weights': 'Balanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 20:57:31,722] Trial 4 finished with value: 0.835820895522388 and parameters: {'depth': 3, 'iterations': 1796, 'learning_rate': 0.15228219866018994, 'l2_leaf_reg': 30.516288325117614, 'random_strength': 6.84642412110064, 'fold_permutation_block': 5, 'auto_class_weights': 'Balanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 20:58:27,015] Trial 5 finished with value: 0.8407960199004975 and parameters: {'depth': 5, 'iterations': 318, 'learning_rate': 0.1893864286181004, 'l2_leaf_reg': 86.78320809927679, 'random_strength': 28.93734138200741, 'fold_permutation_block': 4, 'auto_class_weights': 'Balanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 20:58:32,313] Trial 6 finished with value: 0.4228855721393035 and parameters: {'depth': 3, 'iterations': 1541, 'learning_rate': 0.07097949546172172, 'l2_leaf_reg': 12.15993625481637, 'random_strength': 18.7580309065765, 'fold_permutation_block': 3, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 20:58:51,698] Trial 7 finished with value: 0.835820895522388 and parameters: {'depth': 4, 'iterations': 192, 'learning_rate': 0.2638228502462807, 'l2_leaf_reg': 16.146613355224744, 'random_strength': 5.593119452099838, 'fold_permutation_block': 4, 'auto_class_weights': 'Balanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 20:59:12,124] Trial 8 finished with value: 0.835820895522388 and parameters: {'depth': 4, 'iterations': 199, 'learning_rate': 0.27936919842289315, 'l2_leaf_reg': 20.893112105224724, 'random_strength': 7.182891316754112, 'fold_permutation_block': 9, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 20:59:58,394] Trial 9 finished with value: 0.8706467661691543 and parameters: {'depth': 4, 'iterations': 1075, 'learning_rate': 0.25729727155434184, 'l2_leaf_reg': 20.065072130956217, 'random_strength': 12.461065240684672, 'fold_permutation_block': 4, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 21:00:34,647] Trial 10 finished with value: 0.8159203980099502 and parameters: {'depth': 5, 'iterations': 1955, 'learning_rate': 0.12150911792093146, 'l2_leaf_reg': 44.684415050048955, 'random_strength': 13.15302933624816, 'fold_permutation_block': 2, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 21:01:53,989] Trial 11 finished with value: 0.8706467661691543 and parameters: {'depth': 5, 'iterations': 1142, 'learning_rate': 0.20859809232738635, 'l2_leaf_reg': 36.901907717464795, 'random_strength': 13.357122436489316, 'fold_permutation_block': 5, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 21:02:02,542] Trial 12 finished with value: 0.681592039800995 and parameters: {'depth': 3, 'iterations': 1560, 'learning_rate': 0.14393130096276732, 'l2_leaf_reg': 65.90177608665992, 'random_strength': 12.363045582643561, 'fold_permutation_block': 6, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 21:02:30,086] Trial 13 finished with value: 0.8706467661691543 and parameters: {'depth': 4, 'iterations': 600, 'learning_rate': 0.29526117770911325, 'l2_leaf_reg': 11.367024770732472, 'random_strength': 11.593040879411143, 'fold_permutation_block': 2, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 21:03:50,379] Trial 14 finished with value: 0.8706467661691543 and parameters: {'depth': 5, 'iterations': 1135, 'learning_rate': 0.24422784431277156, 'l2_leaf_reg': 32.25617151247171, 'random_strength': 17.165493454673907, 'fold_permutation_block': 10, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 21:04:06,268] Trial 15 finished with value: 0.7263681592039801 and parameters: {'depth': 4, 'iterations': 1629, 'learning_rate': 0.17280516967024498, 'l2_leaf_reg': 47.66391173331312, 'random_strength': 9.539926654295211, 'fold_permutation_block': 4, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 21:04:23,582] Trial 16 finished with value: 0.7810945273631841 and parameters: {'depth': 4, 'iterations': 1339, 'learning_rate': 0.19882815901833228, 'l2_leaf_reg': 65.20683139768279, 'random_strength': 15.580276607023404, 'fold_permutation_block': 6, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 21:04:46,074] Trial 17 finished with value: 0.7512437810945274 and parameters: {'depth': 5, 'iterations': 1994, 'learning_rate': 0.0343056317093067, 'l2_leaf_reg': 26.29545078477222, 'random_strength': 21.825125205719925, 'fold_permutation_block': 5, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 21:04:53,393] Trial 18 finished with value: 0.6716417910447762 and parameters: {'depth': 3, 'iterations': 491, 'learning_rate': 0.09810552493004435, 'l2_leaf_reg': 41.425842354122864, 'random_strength': 10.34072516108372, 'fold_permutation_block': 3, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 21:05:11,435] Trial 19 finished with value: 0.7960199004975125 and parameters: {'depth': 4, 'iterations': 940, 'learning_rate': 0.23539425456450588, 'l2_leaf_reg': 96.47413031244571, 'random_strength': 15.328706343636622, 'fold_permutation_block': 3, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 21:06:13,339] Trial 20 finished with value: 0.8805970149253731 and parameters: {'depth': 5, 'iterations': 1350, 'learning_rate': 0.25463227334435456, 'l2_leaf_reg': 22.869301845367, 'random_strength': 21.625766424855872, 'fold_permutation_block': 7, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 1 with value: 0.8805970149253731.
[I 2025-07-01 21:07:08,994] Trial 21 finished with value: 0.8955223880597015 and parameters: {'depth': 5, 'iterations': 1299, 'learning_rate': 0.25338047694849597, 'l2_leaf_reg': 10.39306565177209, 'random_strength': 26.057807222448986, 'fold_permutation_block': 7, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:08:05,373] Trial 22 finished with value: 0.8855721393034826 and parameters: {'depth': 5, 'iterations': 1303, 'learning_rate': 0.21874716008263903, 'l2_leaf_reg': 10.605368707909983, 'random_strength': 24.571876083325684, 'fold_permutation_block': 7, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:09:01,486] Trial 23 finished with value: 0.8905472636815921 and parameters: {'depth': 5, 'iterations': 1790, 'learning_rate': 0.21280446257811209, 'l2_leaf_reg': 13.174164519807434, 'random_strength': 25.521761624575596, 'fold_permutation_block': 8, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:09:19,128] Trial 24 finished with value: 0.6865671641791045 and parameters: {'depth': 5, 'iterations': 1288, 'learning_rate': 0.18095688181180786, 'l2_leaf_reg': 30.787561540101738, 'random_strength': 26.904970391419184, 'fold_permutation_block': 8, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:10:08,107] Trial 25 finished with value: 0.8606965174129353 and parameters: {'depth': 5, 'iterations': 1754, 'learning_rate': 0.2885223961756549, 'l2_leaf_reg': 17.699289087699576, 'random_strength': 24.587997685852795, 'fold_permutation_block': 8, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:10:56,121] Trial 26 finished with value: 0.8756218905472637 and parameters: {'depth': 5, 'iterations': 1477, 'learning_rate': 0.21643803712823984, 'l2_leaf_reg': 10.302944566013807, 'random_strength': 29.615413103285714, 'fold_permutation_block': 9, 'auto_class_weights': 'Balanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:12:38,176] Trial 27 finished with value: 0.8805970149253731 and parameters: {'depth': 5, 'iterations': 933, 'learning_rate': 0.16516900891222794, 'l2_leaf_reg': 28.146240677161444, 'random_strength': 23.268098033212265, 'fold_permutation_block': 9, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:13:51,750] Trial 28 finished with value: 0.8756218905472637 and parameters: {'depth': 5, 'iterations': 1204, 'learning_rate': 0.24614581512485928, 'l2_leaf_reg': 37.376177006024484, 'random_strength': 27.092507766187577, 'fold_permutation_block': 7, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:15:07,703] Trial 29 finished with value: 0.8855721393034826 and parameters: {'depth': 5, 'iterations': 1414, 'learning_rate': 0.27500962362462517, 'l2_leaf_reg': 17.811299390970397, 'random_strength': 24.169846200655886, 'fold_permutation_block': 8, 'auto_class_weights': 'Balanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:15:33,116] Trial 30 finished with value: 0.7562189054726368 and parameters: {'depth': 5, 'iterations': 1663, 'learning_rate': 0.19640724952523533, 'l2_leaf_reg': 53.87326950191877, 'random_strength': 27.250294617325753, 'fold_permutation_block': 10, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:16:48,158] Trial 31 finished with value: 0.8706467661691543 and parameters: {'depth': 5, 'iterations': 1458, 'learning_rate': 0.2738554350502069, 'l2_leaf_reg': 16.798941181458208, 'random_strength': 24.63132853652154, 'fold_permutation_block': 8, 'auto_class_weights': 'Balanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:17:50,826] Trial 32 finished with value: 0.8756218905472637 and parameters: {'depth': 5, 'iterations': 1435, 'learning_rate': 0.26639978900314404, 'l2_leaf_reg': 23.9750351468072, 'random_strength': 22.182755483379488, 'fold_permutation_block': 8, 'auto_class_weights': 'Balanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:19:10,933] Trial 33 finished with value: 0.8905472636815921 and parameters: {'depth': 5, 'iterations': 1241, 'learning_rate': 0.22985632010923493, 'l2_leaf_reg': 15.19498355073521, 'random_strength': 20.175462450187926, 'fold_permutation_block': 7, 'auto_class_weights': 'Balanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:20:14,928] Trial 34 finished with value: 0.8656716417910447 and parameters: {'depth': 5, 'iterations': 988, 'learning_rate': 0.21958898049459535, 'l2_leaf_reg': 10.44069698005627, 'random_strength': 20.758300752581487, 'fold_permutation_block': 6, 'auto_class_weights': 'Balanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:21:33,074] Trial 35 finished with value: 0.8855721393034826 and parameters: {'depth': 5, 'iterations': 799, 'learning_rate': 0.23485419751431774, 'l2_leaf_reg': 15.820497248870328, 'random_strength': 25.70081591443784, 'fold_permutation_block': 7, 'auto_class_weights': 'Balanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:22:33,631] Trial 36 finished with value: 0.8855721393034826 and parameters: {'depth': 5, 'iterations': 1240, 'learning_rate': 0.227527001669972, 'l2_leaf_reg': 24.30227832229567, 'random_strength': 28.38888111774468, 'fold_permutation_block': 7, 'auto_class_weights': 'Balanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:23:19,087] Trial 37 finished with value: 0.8507462686567164 and parameters: {'depth': 5, 'iterations': 1836, 'learning_rate': 0.2098173427052283, 'l2_leaf_reg': 34.885786802552964, 'random_strength': 19.65809517622416, 'fold_permutation_block': 6, 'auto_class_weights': 'Balanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:24:33,577] Trial 38 finished with value: 0.8805970149253731 and parameters: {'depth': 5, 'iterations': 702, 'learning_rate': 0.1916318503539843, 'l2_leaf_reg': 14.316313945857672, 'random_strength': 25.87154397547068, 'fold_permutation_block': 6, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 21 with value: 0.8955223880597015.
[I 2025-07-01 21:25:23,560] Trial 39 finished with value: 0.8557213930348259 and parameters: {'depth': 4, 'iterations': 1714, 'learning_rate': 0.15511305957156518, 'l2_leaf_reg': 68.76848061364151, 'random_strength': 23.476935262422696, 'fold_permutation_block': 9, 'auto_class_weights': 'Balanced'}. Best is trial 21 with value: 0.8955223880597015.

### bird

In [17]:
bird_le = OrdinalEncoder()
bird_df_copy = bird_df.copy()
bird_df_copy['category'] = bird_le.fit_transform(bird_df_copy['category'].values.reshape(-1, 1))
X = bird_df_copy.drop('product_type', axis=1)
y = bird_df_copy['product_type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

def objective(trial):
    params = {
        'verbose': False,
        'loss_function': 'MultiClassOneVsAll',
        'eval_metric': 'Accuracy',
        'task_type': 'GPU',
        'random_seed': 42,
        'border_count': 254
    }
    tune_params = {
        'depth': trial.suggest_int('depth', 3, 5),
        'iterations': trial.suggest_int('iterations', 1000, 2000),
        'learning_rate': trial.suggest_float("learning_rate", 0.03, 0.3),
        'l2_leaf_reg': trial.suggest_float("l2_leaf_reg", 1.0, 50.0),
        'random_strength': trial.suggest_float("random_strength", 1.0, 10.0),
        'fold_permutation_block': trial.suggest_int('fold_permutation_block', 2, 10),
        'auto_class_weights': trial.suggest_categorical("auto_class_weights", ["SqrtBalanced", "Balanced"]),
        # 'colsample_bylevel': trial.suggest_float('colsample_bylevel', 0.5, 1.0),
    }
    catbos_model = CatBoostClassifier(**tune_params, **params)
    catbos_model.fit(
        X=X_train,
        y=y_train,
        use_best_model=True,
        eval_set=(X_test, y_test),
        early_stopping_rounds=100
    )
    test_preds = catbos_model.predict(X_test)
    return accuracy_score(y_test, test_preds)

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20)

with open('params.txt', 'a', encoding = 'utf-8') as f:
    f.write('bird_catboost_' + str(study.best_params) + 'weighted accuracy' + str(study.best_value) + '\n')

[I 2025-07-01 21:25:23,722] A new study created in memory with name: no-name-58523735-732d-4271-bad0-bf4b34972864
[I 2025-07-01 21:26:14,262] Trial 0 finished with value: 0.9235137327616177 and parameters: {'depth': 5, 'iterations': 1351, 'learning_rate': 0.2553043047830163, 'l2_leaf_reg': 15.432087539855766, 'random_strength': 4.898379724358179, 'fold_permutation_block': 5, 'auto_class_weights': 'Balanced'}. Best is trial 0 with value: 0.9235137327616177.
[I 2025-07-01 21:27:02,271] Trial 1 finished with value: 0.9071734847606907 and parameters: {'depth': 5, 'iterations': 1528, 'learning_rate': 0.16293065550822405, 'l2_leaf_reg': 11.283587805570882, 'random_strength': 4.877663604917267, 'fold_permutation_block': 9, 'auto_class_weights': 'Balanced'}. Best is trial 0 with value: 0.9235137327616177.
[I 2025-07-01 21:30:12,823] Trial 2 finished with value: 0.9662765094448951 and parameters: {'depth': 4, 'iterations': 1557, 'learning_rate': 0.23735692203721878, 'l2_leaf_reg': 38.54800171324363, 'random_strength': 3.520632998532285, 'fold_permutation_block': 2, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 21:31:10,451] Trial 3 finished with value: 0.9335960134430409 and parameters: {'depth': 5, 'iterations': 1519, 'learning_rate': 0.2698761101775933, 'l2_leaf_reg': 11.390403171842884, 'random_strength': 1.1937686210461393, 'fold_permutation_block': 4, 'auto_class_weights': 'Balanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 21:32:40,936] Trial 4 finished with value: 0.9617568663808089 and parameters: {'depth': 4, 'iterations': 1761, 'learning_rate': 0.21847155222440875, 'l2_leaf_reg': 11.240163928894827, 'random_strength': 7.415306403694675, 'fold_permutation_block': 3, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 21:34:06,791] Trial 5 finished with value: 0.9636110789199211 and parameters: {'depth': 3, 'iterations': 1921, 'learning_rate': 0.28652861930330953, 'l2_leaf_reg': 16.082448771267465, 'random_strength': 3.45136734647966, 'fold_permutation_block': 9, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 21:35:35,674] Trial 6 finished with value: 0.9318576891876231 and parameters: {'depth': 5, 'iterations': 1672, 'learning_rate': 0.07429515404874151, 'l2_leaf_reg': 1.053488227914206, 'random_strength': 2.829619986050694, 'fold_permutation_block': 2, 'auto_class_weights': 'Balanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 21:40:38,737] Trial 7 finished with value: 0.9661606211612006 and parameters: {'depth': 5, 'iterations': 1584, 'learning_rate': 0.14666050967894734, 'l2_leaf_reg': 30.292559801852125, 'random_strength': 3.2924722205935018, 'fold_permutation_block': 4, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 21:43:13,298] Trial 8 finished with value: 0.9609456483949472 and parameters: {'depth': 4, 'iterations': 1350, 'learning_rate': 0.07841123959877241, 'l2_leaf_reg': 13.787741528472655, 'random_strength': 7.852214606256683, 'fold_permutation_block': 5, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 21:45:59,423] Trial 9 finished with value: 0.9611774249623363 and parameters: {'depth': 4, 'iterations': 1446, 'learning_rate': 0.12960041608304207, 'l2_leaf_reg': 40.92995044442625, 'random_strength': 4.1868810055047625, 'fold_permutation_block': 4, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 21:47:25,054] Trial 10 finished with value: 0.958859659288446 and parameters: {'depth': 3, 'iterations': 1066, 'learning_rate': 0.21483587008209248, 'l2_leaf_reg': 49.967967200962214, 'random_strength': 6.28691638672299, 'fold_permutation_block': 7, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 21:49:42,854] Trial 11 finished with value: 0.9610615366786418 and parameters: {'depth': 4, 'iterations': 1746, 'learning_rate': 0.13589529145170756, 'l2_leaf_reg': 32.65019611198153, 'random_strength': 2.0803953422941843, 'fold_permutation_block': 2, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 21:51:42,337] Trial 12 finished with value: 0.9623363077992815 and parameters: {'depth': 4, 'iterations': 1183, 'learning_rate': 0.20480915680334894, 'l2_leaf_reg': 29.99091477290608, 'random_strength': 9.572983736372407, 'fold_permutation_block': 7, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 21:53:47,901] Trial 13 finished with value: 0.9480820489048557 and parameters: {'depth': 3, 'iterations': 1611, 'learning_rate': 0.038603037782838176, 'l2_leaf_reg': 37.86808290046339, 'random_strength': 3.045960430514615, 'fold_permutation_block': 3, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 21:55:56,327] Trial 14 finished with value: 0.9616409780971144 and parameters: {'depth': 5, 'iterations': 1937, 'learning_rate': 0.17350692949862412, 'l2_leaf_reg': 23.60144105861717, 'random_strength': 1.50224484202327, 'fold_permutation_block': 2, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 21:57:58,261] Trial 15 finished with value: 0.962452196082976 and parameters: {'depth': 4, 'iterations': 1285, 'learning_rate': 0.23690732857506308, 'l2_leaf_reg': 43.66464010411219, 'random_strength': 6.132179806791765, 'fold_permutation_block': 6, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 22:01:18,463] Trial 16 finished with value: 0.9646540734731719 and parameters: {'depth': 5, 'iterations': 1791, 'learning_rate': 0.1821563781053092, 'l2_leaf_reg': 24.5009816884615, 'random_strength': 3.941640877325883, 'fold_permutation_block': 4, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 22:03:32,403] Trial 17 finished with value: 0.961988642948198 and parameters: {'depth': 3, 'iterations': 1611, 'learning_rate': 0.13578118696179997, 'l2_leaf_reg': 33.11144122540416, 'random_strength': 2.2052079355243124, 'fold_permutation_block': 3, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 22:04:07,455] Trial 18 finished with value: 0.8709004519643064 and parameters: {'depth': 4, 'iterations': 1444, 'learning_rate': 0.1040916876787204, 'l2_leaf_reg': 45.35799468750419, 'random_strength': 5.400333728149254, 'fold_permutation_block': 5, 'auto_class_weights': 'Balanced'}. Best is trial 2 with value: 0.9662765094448951.
[I 2025-07-01 22:06:20,027] Trial 19 finished with value: 0.961988642948198 and parameters: {'depth': 4, 'iterations': 1206, 'learning_rate': 0.1909008673977856, 'l2_leaf_reg': 38.14027811400594, 'random_strength': 3.9696482672600033, 'fold_permutation_block': 10, 'auto_class_weights': 'SqrtBalanced'}. Best is trial 2 with value: 0.9662765094448951.

# Сохранение моделей

In [ ]:
for df, reg_power, name in [(beef_df, 0.059269555634620164, 'Говядина'), (pig_df, 0.25481644439042445, 'Свинина'), (mutton_df, 0.3613217052503698, 'Баранина'), (bird_df, 0.03602531078286672, 'Птица')]:
    # old: {beef_df: 0.42335358835241554, pig_df: 0.46292901978098716, mutton_df: 0.13090857438995906, bird_df: 0.0973232033878918
    
    # из-за сильного классового дисбаланса дублирую сэмплы баранины
    df_balanced = df.copy()
    if name == 'Баранина':
        problem_classes = df_balanced[df_balanced['category'].isin(['баранина', 'ягнятина'])]
        for _ in range(3):
            df_balanced = pd.concat([df_balanced, problem_classes], ignore_index=True)
    
    preprocessor = ColumnTransformer([('text', OrdinalEncoder(), [0])], remainder='passthrough')
    pipe = Pipeline(
        steps=[("preprocessor", preprocessor), ("classifier", LogisticRegression(class_weight='balanced', C=reg_power))]
    )
    X = df_balanced.drop('product_type', axis=1)
    y = df_balanced['product_type']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=12, stratify=y)

    pipe.fit(X, y)

    test_preds = pipe.predict(X_test)
    print('test balanced_accuracy', balanced_accuracy_score(y_test, test_preds), 'test accuracy', accuracy_score(y_test, test_preds))

    initial_type = [('str_input', StringTensorType([None, 1])),
                    ('float_input', FloatTensorType([None, 768]))]
    model_onnx = convert_sklearn(pipe, initial_types=initial_type)
    with open(f"{name}_logreg.onnx", "wb") as f:
        f.write(model_onnx.SerializeToString())

test balanced_accuracy 0.9804031581481781 test accuracy 0.953405017921147
test balanced_accuracy 0.9946961464528634 test accuracy 0.9840031213421772
test balanced_accuracy 0.999809305873379 test accuracy 0.9985029940119761
test balanced_accuracy 0.9833035743570144 test accuracy 0.974968130721984

### catboost

Для конвертации в onnx необходимо написать свои функции конвертации для catboost. Код взят с официального туториала https://onnx.ai/sklearn-onnx/auto_tutorial/plot_gexternal_catboost.html

In [29]:
def skl2onnx_parser_castboost_classifier(scope, model, inputs, custom_parsers=None):
    options = scope.get_options(model, dict(zipmap=True))
    no_zipmap = isinstance(options["zipmap"], bool) and not options["zipmap"]

    alias = _get_sklearn_operator_name(type(model))
    this_operator = scope.declare_local_operator(alias, model)
    this_operator.inputs = inputs

    label_variable = scope.declare_local_variable("label", Int64TensorType())
    prob_dtype = guess_tensor_type(inputs[0].type)
    probability_tensor_variable = scope.declare_local_variable(
        "probabilities", prob_dtype
    )
    this_operator.outputs.append(label_variable)
    this_operator.outputs.append(probability_tensor_variable)
    probability_tensor = this_operator.outputs

    if no_zipmap:
        return probability_tensor

    return _apply_zipmap(
        options["zipmap"], scope, model, inputs[0].type, probability_tensor
    )


def skl2onnx_convert_catboost(scope, operator, container):
    """
    CatBoost returns an ONNX graph with a single node.
    This function adds it to the main graph.
    """
    onx = convert_to_onnx_object(operator.raw_operator)
    opsets = {d.domain: d.version for d in onx.opset_import}
    if "" in opsets and opsets[""] >= container.target_opset:
        raise RuntimeError("CatBoost uses an opset more recent than the target one.")
    if len(onx.graph.initializer) > 0 or len(onx.graph.sparse_initializer) > 0:
        raise NotImplementedError(
            "CatBoost returns a model initializers. This option is not implemented yet."
        )
    if (
        len(onx.graph.node) not in (1, 2)
        or not onx.graph.node[0].op_type.startswith("TreeEnsemble")
        or (len(onx.graph.node) == 2 and onx.graph.node[1].op_type != "ZipMap")
    ):
        types = ", ".join(map(lambda n: n.op_type, onx.graph.node))
        raise NotImplementedError(
            f"CatBoost returns {len(onx.graph.node)} != 1 (types={types}). "
            f"This option is not implemented yet."
        )
    node = onx.graph.node[0]
    atts = {}
    for att in node.attribute:
        atts[att.name] = get_attribute_value(att)
    container.add_node(
        node.op_type,
        [operator.inputs[0].full_name],
        [operator.outputs[0].full_name, operator.outputs[1].full_name],
        op_domain=node.domain,
        op_version=opsets.get(node.domain, None),
        **atts,
    )


update_registered_converter(
    CatBoostClassifier,
    "CatBoostCatBoostClassifier",
    calculate_linear_classifier_output_shapes,
    skl2onnx_convert_catboost,
    parser=skl2onnx_parser_castboost_classifier,
    options={"nocl": [True, False], "zipmap": [True, False, "columns"]},
)

In [31]:
train_data = [
    (
        beef_df,
        {
            'depth': 3, 'iterations': 1961, 'learning_rate': 0.24211334049159006, 'l2_leaf_reg': 7.0422324402524605, 
            'random_strength': 9.325586023176506, 'fold_permutation_block': 4, 'auto_class_weights': 'SqrtBalanced'
        },
        'Говядина'
    ),
    (
        pig_df,
        {
            'depth': 5, 'iterations': 1664, 'learning_rate': 0.21384214801999102, 'l2_leaf_reg': 31.460470832453527, 
            'random_strength': 17.770338490574982, 'fold_permutation_block': 4, 'auto_class_weights': 'SqrtBalanced'
        },
        'Свинина'
    ),
    (
        mutton_df,
        {
            'depth': 5, 'iterations': 1299, 'learning_rate': 0.25338047694849597, 'l2_leaf_reg': 10.39306565177209, 
            'random_strength': 26.057807222448986, 'fold_permutation_block': 7, 'auto_class_weights': 'SqrtBalanced'
        },
        'Баранина'
    ),
    (
        bird_df,
        {
            'depth': 4, 'iterations': 1557, 'learning_rate': 0.23735692203721878, 'l2_leaf_reg': 38.54800171324363, 
            'random_strength': 3.520632998532285, 'fold_permutation_block': 2, 'auto_class_weights': 'SqrtBalanced'
        },
        'Птица'
    ),
]


for df, params, name in train_data:

    # из-за сильного классового дисбаланса дублирую сэмплы баранины
    df_balanced = df.copy()
    if name == 'Баранина':
        problem_classes = df_balanced[df_balanced['category'].isin(['баранина', 'ягнятина'])]
        for _ in range(3):
            df_balanced = pd.concat([df_balanced, problem_classes], ignore_index=True)

    X = df_balanced.drop('product_type', axis=1)
    y = df_balanced['product_type']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


    const_params = {
        'verbose': False,
        'loss_function': 'MultiClassOneVsAll',
        'eval_metric': 'Accuracy',
        'task_type': 'GPU',
        'random_seed': 42,
        'border_count': 254,
    }

    preprocessor = ColumnTransformer([('text', OrdinalEncoder(), [0])], remainder='passthrough')
    preprocessor.fit(X)
    pipe = Pipeline(
        steps=[("preprocessor", preprocessor), ("classifier", CatBoostClassifier(**const_params, **params))]
    )

    pipe.fit(
        X=X_train,
        y=y_train,
        classifier__use_best_model=True,
        classifier__eval_set=(preprocessor.transform(X_test), y_test),
        classifier__early_stopping_rounds=100
    )

    test_preds = pipe.predict(X_test)
    print('test balanced_accuracy', balanced_accuracy_score(y_test, test_preds), 'test accuracy', accuracy_score(y_test, test_preds))


    initial_type = [('str_input', StringTensorType([None, 1])),
                ('float_input', FloatTensorType([None, 768]))]

    model_onnx = convert_sklearn(
        pipe,
        f"pipeline_catboost",
        initial_types=initial_type,
    )
    with open(f"{name}_catboost.onnx", "wb") as f:
        f.write(model_onnx.SerializeToString())

test balanced_accuracy 0.8017892579731764 test accuracy 0.9278673835125448
test balanced_accuracy 0.768240413852875 test accuracy 0.9371829886851346
test balanced_accuracy 0.9975845410628018 test accuracy 0.9985029940119761
test balanced_accuracy 0.8209066702051491 test accuracy 0.9662765094448951